routes/web.php
<?php

Route::namespace('manager')->group(function(){

    Route::get('/dashboardManager', 'homeController@index')->name('manager.home');

    Route::group(['prefix' => 'barang', 'as' =>'barangManager.'], function(){
        Route::get('/pengadaanBarang', 'barangController@index')->name('index');
    });

    Route::group(['prefix' => 'pembangunan', 'as' =>'pembangunanManager.'], function(){
        Route::get('/kebutuhanPembangunan', 'pembangunanController@index')->name('index');
    });
});

Route::namespace('perencanaan')->group(function(){

    Route::get('/dashboardPerencanaan', 'homeController@index')->name('perencanaan.home');

    Route::group(['prefix' => 'barangPerencanaan', 'as' =>'barangPerencanaan.'], function(){
        Route::get('/index', 'barangController@index')->name('index');
        Route::get('/create', 'barangController@create')->name('create');
    });

    Route::group(['prefix' => 'pembangunanPerencanaan', 'as' =>'pembangunanPerencanaan.'], function(){
        Route::get('/index', 'pembangunanController@index')->name('index');
        Route::get('/create', 'pembangunanController@create')->name('create');
    });

    Route::group(['prefix' => 'stockPerencanaan', 'as' =>'stockPerencanaan.'], function(){
        Route::get('/index', 'stockBarangController@index')->name('index');
    });
});

Route::namespace('kontruksi')->group(function(){

    Route::get('/dashboardKontruksi', 'homeController@index')->name('kontruksi.home');

    Route::group(['prefix' => 'barangKontruksi', 'as' =>'barangKontruksi.'], function(){
        Route::get('/index', 'barangController@index')->name('index');
        Route::get('/create', 'barangController@create')->name('create');
    });

    Route::group(['prefix' => 'pembangunanKontruksi', 'as' =>'pembangunanKontruksi.'], function(){
        Route::get('/index', 'pembangunanController@index')->name('index');
    });

    Route::group(['prefix' => 'stockKontruksi', 'as' =>'stockKontruksi.'], function(){
        Route::get('/index', 'stockBarangController@index')->name('index');
        Route::get('/create', 'stockBarangController@create')->name('create');
    });
});

app/Http/Controllers/perencanaan/barangController.php
<?php

namespace App\Http\Controllers\perencanaan;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class barangController extends Controller{

    public function index(){
        return view('perencanaan.barang.index');
    }

    public function create(){
        return view('perencanaan.barang.create');
    }

    public function store(Request $request){
        
    }

    public function show($id){
        
    }

    public function edit($id){
        
    }

    public function update(Request $request, $id){
        
    }

    public function destroy($id){
        
    }
}

app/Http/Controllers/perencanaan/homeController.php
<?php

namespace App\Http\Controllers\perencanaan;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class homeController extends Controller{

    public function index(){
        return view('perencanaan.home.index');
    }

    public function create(){
        
    }

    public function store(Request $request){
        
    }

    public function show($id){
        
    }

    public function edit($id){
        
    }

    public function update(Request $request, $id){
        
    }

    public function destroy($id){
        
    }
}

app/Http/Controllers/perencanaan/pembangunanController.php
<?php

namespace App\Http\Controllers\perencanaan;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class pembangunanController extends Controller{

    public function index(){
        return view('perencanaan.pembangunan.index');
    }

    public function create(){
        return view('perencanaan.pembangunan.create');
    }

    public function store(Request $request){
        
    }

    public function show($id){
        
    }
    
    public function edit($id){
        
    }

    public function update(Request $request, $id){
        
    }

    public function destroy($id){
        
    }
}

app/Http/Controllers/perencanaan/stockBarangController.php
<?php

namespace App\Http\Controllers\perencanaan;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class stockBarangController extends Controller{

    public function index(){
        return view ('perencanaan.stock.index');
    }

    public function create(){
        
    }

    public function store(Request $request){
        
    }

    public function show($id){
        
    }

    public function edit($id){
        
    }

    public function update(Request $request, $id){
        
    }

    public function destroy($id){
        
    }
}

resources/views/perencanaan/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Perencanaan | Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{asset('assets/manager/plugins/fontawesome-free/css/all.min.css')}}">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{{asset('assets/manager/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/manager/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/manager/plugins/jqvmap/jqvmap.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/manager/dist/css/adminlte.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/manager/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/manager/plugins/daterangepicker/daterangepicker.css')}}">
    <link rel="stylesheet" href="{{asset('assets/manager/plugins/summernote/summernote-bs4.css')}}">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
@yield('extrahead')
<body class="hold-transition sidebar-mini layout-fixed">
	<div class="wrapper">
		<nav class="main-header navbar navbar-expand navbar-white navbar-light">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
				</li>
				<li class="nav-item d-none d-sm-inline-block">
					<a href="index3.html" class="nav-link">Home</a>
				</li>
				<li class="nav-item d-none d-sm-inline-block">
					<a href="#" class="nav-link">Contact</a>
			    </li>
			</ul>
			<form class="form-inline ml-3">
				<div class="input-group input-group-sm">
					<input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
					<div class="input-group-append">
						<button class="btn btn-navbar" type="submit">
							<i class="fas fa-search"></i>
						</button>
					</div>
				</div>
			</form>
			<ul class="navbar-nav ml-auto">
				<li class="nav-item dropdown">
					<a class="nav-link" data-toggle="dropdown" href="#">
						<i class="far fa-comments"></i>
						<span class="badge badge-danger navbar-badge">3</span>
					</a>
					<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
						<a href="#" class="dropdown-item">
							<!-- Message Start -->
							<div class="media">
								<img src="{{asset('assets/manager/dist/img/user1-128x128.jpg')}}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
								<div class="media-body">
									<h3 class="dropdown-item-title">
										Brad Diesel
										<span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
									</h3>
									<p class="text-sm">Call me whenever you can...</p>
									<p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
								</div>
							</div>
						</a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <div class="media">
                            <img src="{{asset('assets/manager/dist/img/user8-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    John Pierce
                                    <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">I got your message bro</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#" class="dropdown-item">
                        <div class="media">
                            <img src="{{asset('assets/manager/dist/img/user3-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                            <div class="media-body">
                                <h3 class="dropdown-item-title">
                                    Nora Silvester
                                    <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                </h3>
                                <p class="text-sm">The subject goes here</p>
                                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    	<a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                	</div>
           	 	</li>
				<li class="nav-item dropdown">
					<a class="nav-link" data-toggle="dropdown" href="#">
						<i class="far fa-bell"></i>
						<span class="badge badge-warning navbar-badge">15</span>
					</a>
					<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
						<span class="dropdown-item dropdown-header">15 Notifications</span>
						<div class="dropdown-divider"></div>
						<a href="#" class="dropdown-item">
							<i class="fas fa-envelope mr-2"></i> 4 new messages
							<span class="float-right text-muted text-sm">3 mins</span>
						</a>
						<div class="dropdown-divider"></div>
						<a href="#" class="dropdown-item">
							<i class="fas fa-users mr-2"></i> 8 friend requests
							<span class="float-right text-muted text-sm">12 hours</span>
						</a>
						<div class="dropdown-divider"></div>
						<a href="#" class="dropdown-item">
							<i class="fas fa-file mr-2"></i> 3 new reports
							<span class="float-right text-muted text-sm">2 days</span>
						</a>
						<div class="dropdown-divider"></div>
						<a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
					</div>
				</li>
				<li class="nav-item">
					<a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
						<i class="fas fa-th-large"></i>
					</a>
				</li>
			</ul>
		</nav>
		<aside class="main-sidebar sidebar-dark-primary elevation-4">
			<a href="index3.html" class="brand-link">
				<img src="{{asset('assets/manager/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
				<span class="brand-text font-weight-light">Perencanaan</span>
			</a>
			<div class="sidebar">
				<div class="user-panel mt-3 pb-3 mb-3 d-flex">
					<div class="image">
						<img src="{{asset('assets/manager/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
					</div>
					<div class="info">
						<a href="#" class="d-block">Alexander Pierce</a>
					</div>
				</div>
				<nav class="mt-2">
					<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
						<li class="nav-item">
							<a href="{{route('perencanaan.home')}}" class="nav-link @yield('dashboard')">
								<i class="nav-icon fas fa-tachometer-alt"></i>
								<p>
									Dashboard
								</p>
							</a>
                    	</li>
						<li class="nav-item">
							<a href="{{route('barangPerencanaan.index')}}" class="nav-link @yield('barang')">
								<i class="nav-icon fas fa-th"></i>
								<p>
									Pengadaan Barang
								</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{route('pembangunanPerencanaan.index')}}" class="nav-link @yield('pembangunan')">
								<i class="nav-icon fas fa-th"></i>
								<p>
									Kebutuhan Pembangunan
								</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="{{route('stockPerencanaan.index')}}" class="nav-link @yield('stock')">
								<i class="nav-icon fas fa-th"></i>
								<p>
									Stock Barang
								</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="#" class="nav-link">
								<i class="nav-icon fas fa-th"></i>
								<p>
									Logout
								</p>
							</a>
						</li>
					</ul>
				</nav>
			</div>
		</aside>
    	@yield('content')
		<footer class="main-footer">
			<strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
			All rights reserved.
			<div class="float-right d-none d-sm-inline-block">
				<b>Version</b> 3.0.0-rc.3
			</div>
		</footer>
		<aside class="control-sidebar control-sidebar-dark"></aside>
	</div>

	<script src="{{asset('assets/manager/plugins/jquery/jquery.min.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
	<script>
		$.widget.bridge('uibutton', $.ui.button)
	</script>
	<script src="{{asset('assets/manager/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/chart.js/Chart.min.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/sparklines/sparkline.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/moment/moment.min.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/daterangepicker/daterangepicker.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/summernote/summernote-bs4.min.js')}}"></script>
	<script src="{{asset('assets/manager/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
	<script src="{{asset('assets/manager/dist/js/adminlte.js')}}"></script>
	<script src="{{asset('assets/manager/dist/js/pages/dashboard.js')}}"></script>
	<script src="{{asset('assets/manager/dist/js/demo.js')}}"></script>
@yield('extrascript')
</body>
</html>